# minimal docker-compose.yaml
#
# just start unbound for a quick check

version: '3'

services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
#   volumes:
#     - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
#     - ./conf.d/:/usr/local/unbound/conf.d/:rw
#     - ./log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
#     - ./zones.d/:/usr/local/unbound/zones.d/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

